package com.salofresh.common.enums;

public enum NotificationType {
    BOOKING_CONFIRMATION,
    BOOKING_REMINDER,
    BOOKING_CANCELLED,
    BOOKING_MODIFIED,
    BOOKING_REJECTED,
    BOOKING_COMPLETED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REFUND_PROCESSED,
    OTP_VERIFICATION,
    EMAIL_VERIFICATION,
    PASSWORD_RESET,
    ACCOUNT_LOCKED,
    SALON_APPROVED,
    SALON_REJECTED,
    SALON_SUSPENDED,
    NEW_REVIEW,
    REVIEW_REPLY,
    WALLET_CREDIT,
    WALLET_DEBIT,
    REWARD_POINTS_EARNED,
    COUPON_APPLIED,
    GENERIC
}
