package com.salofresh.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    BAD_REQUEST,
    VALIDATION_FAILED,
    UNAUTHORIZED,
    FORBIDDEN,
    CONFLICT,
    ACCOUNT_LOCKED,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    OTP_INVALID,
    OTP_EXPIRED,
    RATE_LIMIT_EXCEEDED,
    FILE_UPLOAD_ERROR,
    PAYMENT_FAILED,
    SLOT_UNAVAILABLE,
    INTERNAL_ERROR
}
